### ISSUE TITLE
Error when getting root static folder

### ISSUE THREAD

**Issue by keotl** [keotl/jivago#78]
Static file served from "/". When getting "/", the server returns 500 internal server error.

2019-01-24 10:29:52 [ExceptionFilter] [ERROR]  Traceback (most recent call last):
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/system_filters/error_handling/unknown_exception_filter.py", line 17, in doFilter
    chain.doFilter(request, response)
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/filter_chain.py", line 28, in doFilter
    self.filters[0].doFilter(request, response, self.getNextChain())
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/templating/template_filter.py", line 23, in doFilter
    chain.doFilter(request, response)
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/filter_chain.py", line 28, in doFilter
    self.filters[0].doFilter(request, response, self.getNextChain())
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/request/json_serialization_filter.py", line 17, in doFilter
    chain.doFilter(request, response)
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/filter_chain.py", line 28, in doFilter
    self.filters[0].doFilter(request, response, self.getNextChain())
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/request/http_form_deserialization_filter.py", line 16, in doFilter
    chain.doFilter(request, response)
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/filter_chain.py", line 28, in doFilter
    self.filters[0].doFilter(request, response, self.getNextChain())
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/system_filters/body_serialization_filter.py", line 16, in doFilter
    chain.doFilter(request, response)
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/filter_chain.py", line 28, in doFilter
    self.filters[0].doFilter(request, response, self.getNextChain())
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/system_filters/error_handling/application_exception_filter.py", line 27, in doFilter
    raise e
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/system_filters/error_handling/application_exception_filter.py", line 21, in doFilter
    chain.doFilter(request, response)
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/filter_chain.py", line 28, in doFilter
    self.filters[0].doFilter(request, response, self.getNextChain())
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/system_filters/jivago_banner_filter.py", line 13, in doFilter
    chain.doFilter(request, response)
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/filter/filter_chain.py", line 20, in doFilter
    gotten_response = invoker.invoke(request)
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/invocation/rewrite/path_rewriting_route_handler_decorator.py", line 16, in invoke
    return self.decorated.invoke(ModifiedPathFlyweightRequest(request, self.new_path))
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/invocation/resource_invoker.py", line 29, in invoke
    function_return = method(*parameters)
  File "/home/atreides/Documents/lecture-bingo/venv/lib/python3.6/site-packages/jivago/wsgi/routing/serving/static_file_serving_resource.py", line 12, in serve_file
    with open(self.filepath, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/atreides/Documents/lecture-bingo/web_ui/build/'

**Comment by keotl** [comment]
Fixed.
